### ISSUE TITLE
Build fails on broken dependency to github.com/fsouza/go-dockerclient

### ISSUE THREAD

**Issue by joelcogen** [blake-education/dogestry#4]
Your fork of fsouza/go-dockerclient is outdated, and I guess it still has references to the original repo, which breaks `go get`

As a workaround, I added 

```
RUN mkdir /go/src/github.com/fsouza
RUN git clone -b 0.2.1 https://github.com/fsouza/go-dockerclient.git /go/src/github.com/fsouza/go-dockerclient
```

to the Dockerfile, but this needs a proper fix by either using fsouza's version here, or fixing dependencies on your fork to be self-references.

Unrelated: this is really awesome! So much better than the registry system. I hope the Docker team will leverage your work to revamp the whole thing :+1:

**Comment by deoxxa** [comment]
Yep, this is a thing.

**Comment by michaelneale** [comment]
Yes I see this too: 

package code.google.com/p/gcfg
        imports github.com/blake-education/go-dockerclient
        imports github.com/fsouza/go-dockerclient/engine
        imports github.com/fsouza/go-dockerclient/utils
        imports github.com/fsouza/go-dockerclient/term
        imports github.com/fsouza/go-dockerclient/term
        imports github.com/fsouza/go-dockerclient/term: cannot find package "github.com/fsouza/go-dockerclient/term" in any of:
        /usr/local/go/src/pkg/github.com/fsouza/go-dockerclient/term (from $GOROOT)
        /go/src/github.com/fsouza/go-dockerclient/term (from $GOPATH)
        /go/src/github.com/blake-education/dogestry/vendor/go/src/github.com/fsouza/go-dockerclient/term
